---
# tasks file for ansible-test

- name: "Install Docker"
  package:
    name: "{{ packages[ansible_distribution] }}"
    state: latest

# - name: "Daemon.json"
#   template:
#     src: daemon.json.j2
#     dest: /etc/docker/daemon.json
#   notify: "daemon-restart"

- name: "Install pip packages"
  pip:
    name: "{{ packages_pip }}"
    state: present

# Install nginx
- name: "Create the {{ nginx_base_directory }} directory on the host"
  file:
    path: "{{ nginx_base_directory }}"
    state: 'directory'
    mode: '0755'

- name: 'Put the nginx.conf file in place'
  copy:
    content: "{{ nginx_conf }}"
    dest: "{{ nginx_base_directory }}/nginx.conf"
    mode: '0644'
  notify: 'restart-docker-nginx'

- name: "Copy the default html contents to {{ nginx_base_directory }}/defaults on the host"
  copy:
    src: "{{ nginx_static_html_directory }}/"
    dest: "{{ nginx_base_directory }}/defaults"
    mode: '0644'
  notify: 'restart-docker-nginx'

- name: create directory for conf.d nginx
  file:
    path: "{{ nginx_reverse_proxy_config_directory }}"
    state: directory

- name: deploy reverse proxy configurations
  template:
    src: reverse-proxy.conf.j2
    dest: "{{ nginx_reverse_proxy_config_directory }}/{{ item.config_name }}.conf"
  with_items: "{{ nginx_reverse_proxy_proxies }}"
  notify: 'restart-docker-nginx'

- name: Pull default Docker image
  docker_image:
    name: "nginx:{{ nginx_docker_tag }}"
    source: pull

- name: 'Start the nginx docker container'
  docker_container:
    image: "nginx:{{ nginx_docker_tag }}"
    name: "{{ nginx_container_name }}"
    volumes: "{{ nginx_exposed_volumes }}"
    ports: "{{ nginx_published_ports }}"
    exposed_ports: '{{ nginx_exposed_ports }}'
    ports: ['80:80']
    # networks:
    #   - name: nginx
    network_mode: bridge
    state: 'started'
    restart_policy: 'always'
    # log_driver: 'syslog'
    # log_options:
    #   tag: "{{ nginx_container_name }}"

- meta: flush_handlers

- name: wait for tcp 80 to be up
  wait_for:
    host: localhost
    port: 80

# - name: Allow all access to tcp port 80
#   ufw:
#     rule: allow
#     port: '80'
#     proto: tcp
#   when: ansible_distribution == "Ubuntu"